### ISSUE TITLE
Theme improvements

### ISSUE THREAD

**Issue by XhmikosR** [pi-hole/docs#192]
Some things I noticed while playing around with the repo

1. ~~I'm not sure if we really use Font Awesome; if not we should find a way to disable it - **EDIT**: it seems it's included for the social icons which is an overkill IMO, but an upstream issue, see https://github.com/squidfunk/mkdocs-material/issues/1364~~
2. ~~We should inline or at least combine extra CSS and material CSS which imports the fonts - **EDIT** upstream issue~~
3. IMHO the main text font-size (`14px`) is too small; we should use the default `.8rem`
4. Might be worth either preconnecting or at least DNS prefetching api.github.com - **EDIT** upstream issue but we could just add the template partial and modify it

Some of these issues (1, 4) we might need to report upstream for everyone to benefit

**Comment by XhmikosR** [comment]
I think the only thing we can tackle is the third point.

From playing around I found these quite good, but smaller than the upstream sizes:

```css
.md-nav {
    font-size: .65rem;
    line-height: 1.4;
}

.md-typeset {
    font-size: .7rem;
    line-height: 1.5;
}
```
